### PR TITLE
Added Pause & Resume Functionality to TickableManager

### PR DESCRIPTION
**Pull request by brock555**

### CODE REVIEW

**Comment by svermeulen** [comment]
Thanks - I can see how this would be useful.

I changed it slightly, to address the case when Pause() is called from a Tick() method.  (n this case, I think we probably don't want to call Tick() on the ITickable's after the current one)

**Comment by Soren025** [comment]
@svermeulen I disagree with stopping the remaining calls to `Tick()` if paused within `Tick()`. Mostly because the relation between the tick methods and time. Having one `Tick()` have been called once more often than another `Tick()` may cause time sensitive code to fall out of sync with each other.

I do however agree that if `Pause()` is called within a `Tick()`, you can expect `LateTick()` to not be called. However if `Pause()` is called in any tick method, that type of tick it was called in should finish all of its calls due to the reasons above.

As an alternative I would instead keep the original setup, but add a `bool` property for checking if the `TickableManager` is paused. Remaining `Tick()` calls can decide on their own what to do from that point, maybe even diced to revert the pause.

**Comment by brock555** [comment]
I agree that the remaining objects in the queue should receive the tick before enforcing the pause.

**Comment by svermeulen** [comment]
Yeah this is true..

I can imagine some scenarios where that could cause some subtle, hard to track down issues (eg. if you had two ITickable's using Time.deltaTime to move two objects at the same constant speed)

So I'll revert it back  :)

**Pull request merged**
