### PR TITLE
Fix for Signals to work with value types (like int) when on IL2CPP.

### PR DESCRIPTION
**Pull request by Jamjardavies**
Fix for Signals to work with value types (like int) when on IL2CPP.

Issue lies with order of generic types - could be issue with the IL2CPP conversion with Unity.

### CODE REVIEW

**Comment by svermeulen** [comment]
Thanks.  Never would have guessed that changing the order of the generic args would fix this issue  :)

**Comment by whatwapp** [comment]
> changing the order of the generic args

this is a breaking change. you should have incremented the **major** version (and warned in the release notes that existing signals with args will not compile)

**Comment by luispedrofonseca** [comment]
This fix is not working for me for some reason. Using the latest stable Unity version (2017.4.3) and Zenject 5.5.1

I have a Signal like this:
`public class PlayerScoreUpdatedSignal : Signal<PlayerScoreUpdatedSignal, int>`

and I get the AOT error when compiling for iOS. The helper Ref class provided on the docs solves the problem though.

**Comment by svermeulen** [comment]
The way signals work has changed in version 6 so this issue will go away anyway.

**Pull request merged**
