### PR TITLE
FacadeFactory to implement IFactory

### PR DESCRIPTION
**Pull request by green-coder**
Made FacadeFactory implement IFactory, it is needed for the issue #83.

### CODE REVIEW

**Comment by green-coder** [comment]
Ok, I think this PR is done. Please review and merge it if you find no problem.

**Comment by green-coder** [comment]
Added a dedicated function for binding a FacadeFactory.

It can be used like this:

```
Container.BindIFactory<IFacade>()
    .ToFacadeFactory<MyModuleFacade, MyModuleFacade.Factory>(MyModuleFacadeInstaller);
```

**Comment by svermeulen** [comment]
Yep, this makes a lot of sense.  I'm going to add an example in the unit tests then it should be good.

**Comment by svermeulen** [comment]
Had to make a few adjustments to it but it's merged now.  Also, I noticed you added optional arguments to one of the ToCustomFactory methods, which was then forwarded on to the Instantiate.  Can you have a separate bind command for those?  Passing arguments into the bind commands for use in instantiate isn't really done anywhere else so I removed this for now.

**Comment by green-coder** [comment]
Thank you for your adjustments. I feel stupid for forgetting the parameters in the `IFactory`.

My change to `ToCustomFactory(param object[] args)` was prior to creating `ToFacadeFactory(Action<DiContainer> installer)`, the argument was for the facade's container installer. Feel free to remove this change, it is no longer needed for my use cases and I am not sure if it will be needed for the user's classes (users can always use [currying](https://en.wikipedia.org/wiki/Currying) to avoid using any parameter at all).

**Pull request closed without merging**
