### PR TITLE
Container rename

### PR DESCRIPTION
**Pull request by gromchen**
In order to remove collision of names ("_container" is protected), injected "Container" is renamed to "DiContainer" and "_container" to "Container".

### CODE REVIEW

**Comment by jonstvns** [comment]
Why do you need to rename "_container" to "Container"? Yes, yes, the MS docs say protected fields should be PascalCase, but they also say to avoid public/protected fields whenever possible.

What you actually want to do is change "_container" to private and provide a get for the "Container" property. Now you're following best practice while still sticking to the framework conventions.

However, all of these changes will break any user code that accesses "_container" in a derived class, which is every project due to MonoInstaller. It's really not worth the hassle unless there's already a major version change that breaks things.

**Comment by svermeulen** [comment]
I actually wasn't aware that the common convention is to make protected fields PascalCase.  I like the change, but like Limyc said, it will break all existing installers.

It's probably annoying that Zenject forces a convention on you to use underscores for private/protected members, so making the getter of the property protected, and changing _container to be private, would help address that as well

`Container.Bind<IDependencyRoot>().ToSingle<DependencyRootStandard>();` instead of `_container.Bind<IDependencyRoot>().ToSingle<DependencyRootStandard>();` is also quite readable if not more readable.

I'll leave this item open until the next major version change and keep this as an option.  There's actually a few other changes I have in the works that break the API a bit as well.

**Comment by gromchen** [comment]
I guess it's not a problem for anybody to use container with underscore (and it's great code convention for private fields) but usually when you are looking for something public or protected you expect this to start with upper letter. So right now intensions of containers are not clear until you go to source code. And I agree with Limyc if it's appropriate _container should be private and property Container should be with protected getter.

**Comment by svermeulen** [comment]
This change has been merged into the develop branch, which will be merged in when stable

**Pull request closed without merging**
