### PR TITLE
Generalize SceneContext.autoRun as RunnableContext

### PR DESCRIPTION
**Pull request by mysticfall**
Allow lazy initialization of GameObjectContext or ProjectContext.

### CODE REVIEW

**Comment by mysticfall** [comment]
Rebased to resolve conflict.

**Comment by mysticfall** [comment]
I'm sorry if I'm impatient, but is there any reason why you haven't review my PR yet?

I find it a bit odd that other PRs getting merged without much delay while mine gets no update for over 2 months.

Please let me know, if there's anything I can do to speed up the process. Thanks.

**Comment by svermeulen** [comment]
Sorry, you're right that it's very much overdue for me to take a look at this one.   There isn't any particular reason why I haven't yet other than this change seeming more involved than the others

It looks good besides one thing:  I can understand the need for this with GameObjectContext, but I'm not sure about having this flag inside ProjectContext.  What if instead of that, we move the line `ProjectContext.Instance.EnsureIsInitialized` to be inside `SceneContext.RunInternal`?  That way, ProjectContext will not be initialized until the first scene context is initialized.  This seems better to me because otherwise it introduces the potential for someone to have ProjectContext.autoRun set to false while attempting to 'run' a scenecontext, which will throw exceptions.

**Comment by mysticfall** [comment]
@svermeulen Please don't worry. Even though my own project relies on this feature, most likely I'm the only user so far, so no real hurry :)

Anyway, I'll be glad to modify my commits but I'm not sure if I understood you correctly. I thought it was impossible to initialize the context hierarchy in reverse order, for example, what should we do if the said scene context depends on another component defined in the project context?

With my suggested modifications, it allows to trigger context hierarchy initialization at any level (not just for scene contexts, which has been already possible) in lazy manner. But the order of the initialization is unchanged, so it always cascades down the hierarchy.

I might be talking nonsense, since my memory of the internal workings of _Zenject_ has become rather vague now.

Please let me know if I understand you correctly. Thanks!

**Comment by svermeulen** [comment]
I haven't tested it, but from reading the code diffs, I'm guessing that this change won't work properly if you set ProjectContext to have autoRun set to false, and then create a scene with a SceneContext where autoRun is left as true.

It would be worth confirming that but that is my guess.  So my thinking was that we could change it so that ProjectContext does not have an autoRun property, and always just runs when the first SceneContext runs.  The issue with that is that it stands right now, I think the ProjectContext will be run even in cases where a SceneContext has autoRun set to false, because of the line `ProjectContext.Instance.EnsureIsInitialized` inside SceneContext.Awake.  So the idea would be to move that to RunInternal, and then we could safely avoid initializing ProjectContext by just making sure not to run any SceneContexts

When I have some more time I'll actually confirm some of these things

**Comment by mysticfall** [comment]
I thought the relationship between `SceneContext` and `GameObjectContext` was the same with that between `ProjectContext` and `SceneContext`, so the parent context triggers initialization of child contexts but not vice versa.

And if the framework currently allows `GameObjectContext`s to be added to a `SceneContext` which is set to be initialized lazily (which is already a supported feature), I thought the same can be applied between `ProjectContext` and `SceneContext`, so the parent can be set to lazily initialized without affecting its children.

It was my assumption that `SceneContext.autoRun` would be referenced only after when it's requested to be initialized by its parent, `ProjectContext`, rather than setting it to `false` would trigger initialization upward the hierarchy, ignoring ancestors' `autoRun` property.

But my memory has become quite vague about the internals by now, and I might have missed something, or misinterpreted the code.

So, I'll examine the code and test it again to make sure it won't break the existing behaviour as soon as I can.

Thanks much for the input!

**Comment by svermeulen** [comment]
> I thought the relationship between SceneContext and GameObjectContext was the same with that between ProjectContext and SceneContext, so the parent context triggers initialization of child contexts but not vice versa.

Unfortunately no.  The entry point for the scene is SceneContext, so that's always what gets triggered first.  SceneContext then triggers ProjectContext.

GameObjectContext's are different, because they actually get triggered when they get injected by SceneContext, which is why it works as you expect when you set the SceneContext to not auto run.

My guess is that you can see what I mean pretty easily by marking ProjectContext as not auto run, and then running a scene with SceneContext to see what I mean.  But the workaround I suggest above might work as a solution.  If I get some time soon I'll give it a shot to see

**Comment by mysticfall** [comment]
Sorry for the delay. I rechecked the code finally, and you were absolutely right that it doesn't make sense to make `ProjectContext` to extend from `RunnableContext`, as it cannot be lazily initialized in its current status.

I made the changes as you suggested and updated my PR.

**Comment by svermeulen** [comment]
After reviewing this I rebased it onto master, then realized I should have merged it instead, but that's pushed now.  So you might have some issues syncing your own branch again.  Anyway, it's added now  :)   Thanks for following through with this.

**Comment by mysticfall** [comment]
Thanks much! :)

**Pull request closed without merging**
