### PR TITLE
ZenjectAllowDuringValidation now works on interfaces #284

### PR DESCRIPTION
**Pull request by marsermd**

### CODE REVIEW

**Comment by svermeulen** [comment]
Thanks

**Comment by svermeulen** [comment]
I had to revert this since it broke on UWP.  If you can get that method compiling on UWP we can re-add it though

**Comment by marsermd** [comment]
@svermeulen, sorry to hear that.
Unfortunately I don't have a win8 or higher, so I can't build for UWP and hence can't validate my code.

**Comment by svermeulen** [comment]
No problem - it's my fault for not having a CI server set up to catch this kind of thing

**Pull request merged**
