### PR TITLE
Add static CodeInstallers so we can programmatically create the whole Ze...

### PR DESCRIPTION
**Pull request by darl2ng**
...nject context

I'm sure there must be better ways to do this. I'm new to this stuff so here what I do:

```
        GameObject game = new GameObject(ZENJECT_GO);
        NetworkInstaller networkInstaller = (NetworkInstaller)game.AddComponent(typeof(NetworkInstaller));
        List<MonoInstaller> list = new List<MonoInstaller>();
    list.Add(networkInstaller);
    CompositionRoot.CodeInstallers=list.ToArray();                
        game.AddComponent(typeof(CompositionRoot));
```

### CODE REVIEW

**Comment by svermeulen** [comment]
You can programmatically add installers by executing lines like the following in an existing installer:

```
Container.Bind<IInstaller>().To<MyCustomInstaller>();
```

You still need one installer hooked up manually in your scene to the composition root but otherwise you can trigger all your installers from code by using Bind<>.  Does that get you what you want?

**Comment by svermeulen** [comment]
Also, if the installer is entirely in code and not in the scene then it doesn't have to be a MonoInstaller.  You can just inherit from Installer instead.

**Comment by darl2ng** [comment]
It was the first thing I tried but since the Container was empty you had to wait for its construction and then it would be too late for some logic such as IInitialiable to be called.

**Comment by darl2ng** [comment]
If I had one installer hooked up manually then there is no problem. What I'm trying to do is make it entirely in code. I guess the best way to do this would be to somehow expose the registration of generic installers such as StandardUnityInstaller ...

**Comment by svermeulen** [comment]
Oh I understand what you mean now.  I haven't encountered the need to create a composition root dynamically so this never even occurred to me.  I think the way you did it in your pull request is really the only way to do this, so I'll see about adding something like that

**Comment by svermeulen** [comment]
Usage:

```
public class TestRunner : MonoInstaller
{
    public void Start()
    {
        CompositionRoot.AddComponent(this.gameObject, this);
    }

    public override void InstallBindings()
    {
        // add bindings
    }
}
```

**Pull request closed without merging**
